In [1]:
print("Hello World")

Hello World


In [22]:
#import data from csv 
dataset = np.genfromtxt("dataset.csv", skip_header=1, delimiter=",", filling_values=40)

In [7]:
dataset

array([[70., 75., 80., 30.],
       [75., 80., 90., 68.],
       [65., 77., 60., 90.],
       [40., 60., 55., 75.]])

In [8]:
dataset.min()

30.0

In [9]:
dataset.max()

90.0

In [12]:
dataset.sum(axis=0) #menjumlahkan seluruh data baris

array([250., 292., 285., 263.])

In [13]:
dataset.sum(axis=1) #menjumlahkan seluruh data kolom

array([255., 313., 292., 230.])

In [23]:
dataset.mean(axis=0)

array([62.5 , 73.  , 71.25, 65.75])

In [21]:
np.percentile(dataset[:,0], 75) #Q3

71.25

In [20]:
np.percentile(dataset[:,0], 25) #Q1

58.75

In [22]:
np.mean(dataset[:,0])

62.5

In [1]:
# np.append(dataset[80,70,76,90], axis=1) cara ngeappend data

In [ ]:
#image processing

In [1]:
import numpy as np

In [49]:
myArray = np.array([1,2,3,4,5,6])
print(myArray)

[1 2 3 4 5 6]


In [10]:
myArray[1:3]

array([2, 3])

In [14]:
myArray[myArray > 3]

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [47]:
array2D = np.array(([1,2,3,4],[4,5,6,7],[8,9,10,11]))
print(array2D)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
array2D[1,1:3]

array([5, 6])

In [21]:
array2D[0:,:3]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [23]:
dataset

array([[70., 75., 80., 30.],
       [75., 80., 90., 68.],
       [65., 77., 60., 90.],
       [40., 60., 55., 75.]])

In [25]:
dataset.shape

(4, 4)

In [28]:
dataset.mean(axis = 1)

array([63.75, 78.25, 73.  , 57.5 ])

In [38]:
myArangeArray = np.arange(start=1, stop=10, step=1)
myArangeArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
myEmptyArray = np.empty(shape = (3,3))
myEmptyArray

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 4.80231808e-321],
       [8.01092456e-307, 7.56598448e-307, 3.56169948e-317]])

In [41]:
array2D.ndim

2

In [44]:
ndarray.ndim(array2D)

NameError: name 'ndarray' is not defined

In [43]:
np.ndim(myArray)

1

In [45]:
np.size(myArray)

5

In [51]:
reshape_myArray = np.reshape(myArray, (2,3))
print(reshape_myArray)

[[1 2 3]
 [4 5 6]]


In [54]:
np.ndim(reshape_myArray)

2

In [56]:
Array1 = np.array([1,2,3,4,5])
Array2 = np.array([6,7,8,9])
print(Array1*Array2)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [59]:
myMatrices = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myMatrices)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
myMatrices.ndim

2